# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namelist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word1', models.CharField(max_length=20)),
                ('word2', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playundercover.Pair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playundercover.User')),
            ],
        ),
        migrations.AddField(
            model_name='pair',
            name='season',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='playundercover.Season'),
        ),
        migrations.AddField(
            model_name='namelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playundercover.User'),
        ),
    ]
