# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playundercover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='season',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='playundercover.Season'),
        ),
    ]
